Urbans_Sneakers/Cart/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import add_product,clean_cart,delete_product,subtract_product,cart,add_product_cart


app_name='cart'

urlpatterns = [
    path('add_product/<int:pk>/', add_product, name='add_product'),
    path('add_product_cart/<int:pk>/', add_product_cart, name='add_product_cart'),

    path('clean_cart/', clean_cart, name='clean_cart'),

    path('delete_product/<int:pk>/', delete_product, name='delete_product'),

    path('subtract_product/<int:pk>/', subtract_product, name='subtract_product'),
    
    path('cart/', cart, name='cart'),

    
]

Urbans_Sneakers/Orders/urls.py
from django.urls import path
from Orders.views import process_order,order_list

app_name='order'

urlpatterns = [
    path('process_order/', process_order, name='process_order'),
    path('order_list/', order_list, name='order_list'),
] 

Urbans_Sneakers/Urbans_Sneakers/urls.py
from django.contrib import admin
from django.urls import path,include
from Urbans_Sneakers.views import index,shop,setting,base,customize_page,about
# para las imganes url
from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),

    path('',index),
    path('shop/',shop),
    path('setting/',setting),
    path('base/',base),
    path('about/',about),
    path('customize_page/',customize_page),
    


    path('users/', include('users.urls')),
    path('Productos/', include('Productos.urls')),
    path('Cart/', include('Cart.urls')),
    path('customize_page/', include('customize_page.urls')),
    path('Orders/', include('Orders.urls')),
    path('Contact/', include('Contact.urls')),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Urbans_Sneakers/Cart/views.py
from django.shortcuts import render,redirect
from .cart import Cart
from Productos.models import Product
from django.contrib.auth.decorators import login_required




@login_required(login_url='/users/login')
def cart(request):
    return render (request,'Cart/cart.html')




@login_required(login_url='/users/login')
def add_product(request,pk):
    cart=Cart(request)
    product=Product.objects.get(id=pk)
    cart.add(product=product)
    return redirect ('/Productos/Shop_single/%d/?valido'%pk)

@login_required(login_url='/users/login')
def add_product_cart(request,pk):
    cart=Cart(request)
    product=Product.objects.get(id=pk)
    cart.add(product=product)
    return redirect ('/Cart/cart')





@login_required(login_url='/users/login')
def delete_product(request,pk):
    cart=Cart(request)
    product=Product.objects.get(id=pk)
    cart.delete(product=product)
    return redirect ('/Cart/cart')




@login_required(login_url='/users/login')
def subtract_product(request,pk):
    cart=Cart(request)
    product=Product.objects.get(id=pk)
    cart.subtract(product=product)
    return redirect ('/Cart/cart')




@login_required(login_url='/users/login')  
def clean_cart(request):
    cart=Cart(request)
    cart.clean_cart()
    return redirect ('/Cart/cart')

Urbans_Sneakers/templates/Cart/cart.html
<!DOCTYPE html>
<html lang="en">
  {% extends 'General/base.html' %}



<body> 
    {% block base %}
        {% load static %}
            <section class="h-100 gradient-custom">
                <div class="container py-5">
                <div class="row d-flex justify-content-center my-4">
                    <div class="col-md-8">
                    <div class="card mb-4">
                        <div class="card-header py-3">
                        <h5 class="mb-0">Carrito </h5>
                        </div>

            {% if request.session.cart.items %}
                {% for key, value in request.session.cart.items %}  
        
                    <div class="card-body">
                        <!-- Single item -->
                        <div class="row">
                            <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                            <!-- Image -->
                            <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                              {% if value.img %}
                                <img src="{{ value.img }}"
                                class="w-100" alt="{{ value.model}}" />
                                <a href="#!">
                                <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                                </a>
                              {% else %}
                                <img src="{% static 'img/default.png' %}"
                                class="w-100" alt="{{ value.model}}" />
                                <a href="#!">
                                <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                                </a>
                              {% endif %}
                            </div>
                            <!-- Image -->
                            </div>
            
                            <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                            <!-- Data -->
                            <p><strong>{{value.model}}</strong></p>
                            <p>Color: {{value.coulor}}</p>
                            <p>Stock disponible: {{value.stock}}</p>
                            
                            <!-- <p>Size: M</p> -->
                            
                                    <a href="{% url 'cart:delete_product' value.product_id %}">
                                        <button type="button" class="btn btn-success btn-sm me-1 mb-2" data-mdb-toggle="tooltip"
                                            title="Remove item" >Eliminar producto
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </a>
                              
                            <!-- Data -->
                            </div>
            
                            <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">


                            <!-- Quantity -->
                            <p></p>
                            <div class="d-flex mb-1" >
                      
                                <a href="{% url 'cart:subtract_product' value.product_id %}">
                                

                                    <button class="btn btn-success px-4 me-2">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </a>
                                <div class="form-outline ">
                                    <p  class="form-control" >{{value.cant}}</p>
                                </div>
    
                                <a href="{% url 'cart:add_product_cart' value.product_id %}">
                                    <button class="btn btn-success px-4 ms-2">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </a>
                                
                            </div>
                            <!-- Quantity -->

                            <!-- Price -->
                            <p></p>
                            <p class="text-start text-md-center">
                               Precio: <strong>${{value.price}}</strong>
                            </p>
                            <!-- Price -->
                            </div>
                        </div>
                        <!-- Single item -->

                            <hr class="my-4" />
                    </div>
                    
                {% endfor %}
            {% endif %}
            <!-- vaciar carrito -->
            
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
             <a href="{% url 'cart:clean_cart' %}">
                <button type="button" class="btn btn-success btn-lg "
                    title="Remove cart" >Vaciar carrito
                    <i class="fas fa-trash"></i>
                </button>
            </a>
        </div>
        <p></p>
              </div>
              <div class="card mb-4">
                <div class="card-body">
                  <p><strong>Entrega de envío prevista</strong></p>
                  <p class="mb-0">12.10.2020 - 14.10.2020</p>
                </div>
              </div>
              <div class="card mb-4 mb-lg-0">
                <div class="card-body">
                  <p><strong>Metodos de pago</strong></p>
                  <img class="me-2" width="45px"
                    src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                    alt="Visa" />
                  <img class="me-2" width="45px"
                    src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
                    alt="American Express" />
                  <img class="me-2" width="45px"
                    src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                    alt="Mastercard" />
                  
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4">
                <div class="card-header py-3">
                  <h5 class="mb-0">Resumen</h5>
                </div>
                <div class="card-body">
                  <ul class="list-group list-group-flush">
                    <li
                      class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                      Productos
                      <span>${{total_cart_amount}}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                      Envio
                      <span>Gratis</span>
                    </li>
                    <li
                      class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                      <div>
                        <strong>Total </strong>
                        <strong>
                          <p class="mb-0">(Iva incluido)</p>
                        </strong>
                      </div>
                      <span><strong>${{total_cart_amount}}</strong></span>
                    </li>
                  </ul>
                  {% if request.session.cart.items %}
                  <a href="{% url 'order:process_order' %}"><button type="button" class="btn btn-success btn-lg btn-block">
                    Terminar pedido
                  </button></a>
                  {% endif %}
                  
                </div>            
              </div>      
            </div>           
          </div>
        </div>
      </section>  {% endblock %}

Urbans_Sneakers/templates/Cart/order_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>

    {% extends 'General/base.html' %}

<body>
    {% block base %}
    {% load static %}
 
<div class="container">
		<div class="row">
            <div class="col">
				<table class="table table-striped table-bordered table-hover">
                    <thead>
						<tr> 
							<th>Usuario:</th>
							<th>Producto:</th>
							<th>Cantidad:</th>
                            <th>Numero de pedido:</th>
                            <th>Fecha de pedido:</th>
                           
						</tr>
					</thead>
                    {% for order in order_lists %}
					<tbody>
						<tr>
							<td>{{order.user}}</td>
							<td>{{order.product}}</td>
							<td>{{order.cant}}</td>
                            <td>{{order.order}}</td>
                            <td>{{order.created_id}}</td>
                         
                        
                        </tr>
                                            
					</tbody>
                   
                {% endfor %}
                
       
				</table>
                
			</div>
           
		</div>
         </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
{% endblock %}
</html>